### ISSUE TITLE
Brew installation broken: Couldn't download https://git.io/vgvpD

### ISSUE THREAD

**Issue by tabdulradi** [scalacenter/homebrew-bloop#2]
Hello, I am getting this error when installing bloop via brew:
```bash
$ brew install scalacenter/bloop/bloop
```
> ==> Installing bloop from scalacenter/bloop
> ==> Downloading https://github.com/scalacenter/bloop/releases/download/v1.0.0-M8/install.py
> Already downloaded: /Users/tamerabdulradi/Library/Caches/Homebrew/bloop-1.0.0-M8.py
> ==> python install.py --dest bin --version 1.0.0-M8
> Last 15 lines from /Users/tamerabdulradi/Library/Logs/Homebrew/bloop/01.python:
> 2018-04-03 12:20:49 +0100
> 
> python
> install.py
> --dest
> bin
> --version
> 1.0.0-M8
> 
> Couldn't download https://git.io/vgvpD, please try again.
> 
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
> https://github.com/scalacenter/homebrew-bloop/issues
> 
> /usr/local/Homebrew/Library/Homebrew/exceptions.rb:426:in `block in dump': undefined method `check_for_bad_install_name_tool' for #<Homebrew::Diagnostic::Checks:0x00000103aab758> (NoMethodError)
> Did you mean?  check_for_tap_ruby_files_locations
> 	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `each'
> 	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
> 	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
> 	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'

**Comment by jvican** [comment]
Hey @tabdulradi, I'm not an OSX user but this seems to be an error in your homebrew installation, not the bloop package itself. @Duhemm What are your thoughts on this?

**Comment by tabdulradi** [comment]
hmm, I'll try it out on a different macbook tonight. Thanks for your help.

**Comment by olafurpg** [comment]
I saw a similar error installing older versions of bloop but I haven't encountered it recently. What happens if you run `export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"` first?

**Comment by tabdulradi** [comment]
Hi Olaf, thank for help. I am getting the same error
```
==> Installing bloop from scalacenter/bloop
==> Downloading https://github.com/scalacenter/bloop/releases/download/v1.0.
Already downloaded: /Users/tamerabdulradi/Library/Caches/Homebrew/bloop-1.0.0-M8.py
==> python install.py --dest bin --version 1.0.0-M8
Last 15 lines from /Users/tamerabdulradi/Library/Logs/Homebrew/bloop/01.python:
2018-04-04 11:34:15 +0100

python
install.py
--dest
bin
--version
1.0.0-M8

Couldn't download https://git.io/vgvpD, please try again.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/scalacenter/homebrew-bloop/issues

/usr/local/Homebrew/Library/Homebrew/exceptions.rb:426:in `block in dump': undefined method `check_for_bad_install_name_tool' for #<Homebrew::Diagnostic::Checks:0x00000101cd9680> (NoMethodError)
Did you mean?  check_for_tap_ruby_files_locations
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `each'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
```

My default Python is `2.7.14`, but I have Python `3.6.5` installed as well.

**Comment by jvican** [comment]
Can you clean the installed package (removing it from the cache) and installing it afresh again?

**Comment by tabdulradi** [comment]
The installation worked fine on my personal macbook. I didn't manage to solve the problem with first laptop, but I'll use this one for now. 
I'll close the issue for now, if anyone had the same problem, feel free to revive it.

**Comment by vbachurin** [comment]
I experience the same issue with `1.0.0-M9`: 
```
...
==> python install.py --dest bin --version 1.0.0-M9
Last 15 lines from /Users/vbachurin/Library/Logs/Homebrew/bloop/01.python:
2018-04-10 12:48:21 +0300

python
install.py
--dest
bin
--version
1.0.0-M9

Couldn't download https://git.io/vgvpD, please try again.

```
The file behind the link is `coursier`, which I am able to download using that link. 
Attaching the output of the first `brew install scalacenter/bloop/bloop` run:
[brew-bloop_init.txt](https://github.com/scalacenter/homebrew-bloop/files/1894187/brew-bloop_init.txt)
also the 'verbose' run after cleaning the brew cache:
[brew-bloop_rm-cache-and-verbose.txt](https://github.com/scalacenter/homebrew-bloop/files/1894193/brew-bloop_rm-cache-and-verbose.txt)
The log files mentioned in the latter contain the same info as the output, no sense to attach it.

Hope that will be helpful.
