### ISSUE TITLE
Unable to locate Java executable

### ISSUE THREAD

**Issue by micheal-hill** [scalacenter/homebrew-bloop#5]
Bloop is failing to install, appears to be due to using ASDF to manage my Java install.
```
==> python3 install.py --dest bin --version 1.2.5
Last 15 lines from /Users/${user}/Library/Logs/Homebrew/bloop/01.python3:
2019-01-25 13:26:49 +1100

python3
install.py
--dest
bin
--version
1.2.5

Unable to locate an executable at "/Users/${user}/.asdf/bin/java" (-1)
Downloading Bloop's coursier version, this may take some seconds...
Coursier couldn't create bin/blp-server. Please report an issue.
Command: ['java', '-jar', 'bin/blp-coursier', 'fetch', 'ch.epfl.scala:bloop-frontend_2.12:1.2.5', '-r', 'bintray:scalameta/maven', '-r', 'bintray:scalacenter/releases', '-r', 'https://oss.sonatype.org/content/repositories/staging']
Return code: 2
```
The executable it's looking for exists, but is not a binary file. In fact it is a shell script which delegates to whichever version of java I'm currently using from asdf.
```
> which java
/Users/${user}/.asdf/shims/java
> echo $JAVA_HOME
/Users/${user}/.asdf/installs/java/oracle-8.191
```

**Comment by jvican** [comment]
This looks like an error in coursier rather than our installation script (we don't output the error message). Any idea @alexarchambault ?

**Comment by alexarchambault** [comment]
I’m not sure the problem comes from coursier (maybe nor from bloop actually).

The coursier launcher does nothing fancy (at all) here… It just runs ˋjava -jar /path/to/itself`.

**Comment by jvican** [comment]
@alexarchambault Thanks for the answer.

@micheal-hill It looks like maybe `java_home` is failing here. Could you try running `/usr/libexec/java_home -v 1.8 -F -R --exec java --version` in your computer?

**Comment by micheal-hill** [comment]
@jvican my `java_home` points to the MacOS stub which prompts to install java. I haven't looked too hard to find a way to get `asdf`'s java installation to be recognised by MacOS so far, and it hasn't really been an issue for anything else: my `JAVA_HOME`, `PATH`, etc. all include the version of `java` I'm using from `asdf`.

As I mentioned in the original post; my `java` is located at `/Users/${user}/.asdf/shims/java` but this is a shell script rather than a binary file (The shell script delegates to whichever version of java I'm using at the time or for a particular project). It appears that the bloop installation (be that through `coursier` or otherwise) can see that this file exists but expects it should be a binary file instead of a shell script.

**Comment by micheal-hill** [comment]
Unless is the log message `Unable to locate an executable at "/Users/${user}/.asdf/bin/java" (-1)` a false flag emitted by Homebrew, and the actual error is completely unrelated?

**Comment by jvican** [comment]
I cannot think of any part where we expect a binary file instead of a shell script. I use Jenv to handle java versions in my macOS machines and I've had no problems so far.
  
I don't know how `asdf` completely manages Java versions and won't have time to look at it any time soon, but if you're willing to have a look I'd check the installation script. This is the line where the error seems to happen: https://github.com/scalacenter/bloop/blob/master/bin/install.py#L224. We just shell out to java via Python.

**Comment by jvican** [comment]
@micheal-hill did you eventually figure out what was going on here?

**Comment by micheal-hill** [comment]
@jvican Unfortunately I didn't. I haven't had the time to dig into the issue properly, so for the moment I'm not using bloop.

**Comment by jvican** [comment]
Sounds good, please reopen if you find this error persists again!
